name: Pack alpha packages

on:
  push:
    branches:
      - 'master'
      - 'release/*'
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    uses: creatorflow-io/shared-workflows/.github/workflows/shared-pack.yml@net8
    with:
       Stage: alpha
       Target: |
        6.x
        8.x
    secrets: inherit