name: Pack beta packages

on:  workflow_dispatch


jobs:
  build:
    uses: creatorflow-io/shared-workflows/.github/workflows/shared-pack.yml@net8
    with:
       Stage: beta
       Target: |
        6.x
        8.x
    secrets: inherit