name: Nuget.org Release

on:
  release:
    types:
      - published


jobs:
    build:
      uses: creatorflow-io/shared-workflows/.github/workflows/shared-publish.yml@net8
      with:
        Target: |
          6.x
          8.x
      secrets: inherit
